### ISSUE TITLE
[FEATURE] 인생책 작성

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#116]
## 📄 Description
인생책 작성을 위한 모달 및 책 검색 페이지에서 책을 선택하여 포스팅하는 기능을 구현합니다.

## ✅ TODO
- [ ] 상태관리를 위한 redux 설치
- [ ] 인생책 작성 모달 추가
- [ ] 인생책 업데이트 preview를 위한 컴포넌트 추가
- [ ] 전역 상태관리를 통해 데이터 가져오기
- [ ] 인생책 작성 완료

## 🎸 ETC
화이팅
