### ISSUE TITLE
[Style] 랜딩 페이지 CSS 수정

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#129]
## 📄 Description
랜딩 페이지의 CSS를 최적화합니다.

## ✅ TODO
- [x] Welcome 섹션 CSS 변경 (svg 삭제)
- [x] Footer 섹션 CSS 변경 (svg 삭제)
- [x] LadingItems 섹션 CSS 변경
  - [x] #97  연장선

## 🎸 ETC
기타사항
