### ISSUE TITLE
[FEAT] 사이드 바 구현

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#14]
## 📄 Description
페이지 네비게이션을 담당할 사이드 바 구현

## ✅ TODO
- [x] 어떤 방식으로 구현할 지 사전 협의
- [x] 페이지 네비게이션 구현
- [x] 로그인 안되어있는 경우, 로그인 버튼 표시
- [ ] 로그인 완료시 아래에 유저 이름 및 프로필 사진 출력
- [x] 사이드 바 애니메이션

## 🎸 ETC
작동 방식 협의 필요.
### 1번
``` 
// 〇〇.tsx
return(
<div className="왼쪽“>
  <왼쪽 컴포넌트 />
</div>
<div className="오른쪽“>
  <오른쪽 컴포넌트 />
</div>
•••
)};
```

### 2번
```
// 〇〇.tsx
return (
<왼쪽 컴포넌트 />
<오른쪽 컴포넌트 />
)};
```
두 방식 중 어떤 방식으로 구현할 지 논의 필요함.
- z-index로 아예 사이드바 이외의 영역은 못나오게 구현할 것인가??

**Comment by joshuayeyo** [comment]
## Sidebar 구현 방법
### chakra-ui의 Drawer 사용
[바로가기](https://v2.chakra-ui.com/docs/components/drawer/usage)
### 구현방법
full-size drawer로 구현 후,
헤더에 1번과 같은 방식으로 넣으면 반쪽 꽉 채워지지 않을까 싶음..?
(함 해보입시더)

**Comment by joshuayeyo** [comment]
프사출력 끝나고 이슈 닫을게유?
