### ISSUE TITLE
[FEATURE] 테스트를 위한 테스트 환경 세팅

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#144]
## ✅ TODO
- [x] 테스트 환경 세팅
- [x] ci.yml 수정
- [ ] 예시용 파일 하나 추가 (App.tsx로)
