### ISSUE TITLE
[FEAT] coverImageKey 추가에 따른 프로필 수정 모달 변경

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#189]
## 📄 Description
설명 작성하세요.

## ✅ TODO
- [ ] Cover Image가 없어도 작동하게 구현
- [ ] Cover Image 업로드 기능 구현
- [ ] CSS 새롭게 제작
