### ISSUE TITLE
[Refactor] 인생책 && 책 상세 관련 리팩토링

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#192]
## 📄 Description
새 창이 뜨는 페이지를 변경하고, 새로고침을 해도 모달 창이 닫히지 않도록 변경합니다.

## ✅ TODO
- [ ] 책 검색 페이지로 향하는 로직 수정 && 버튼 조건부 출력
- [ ] 책 선택 시 기존 페이지로 돌아오는 로직 추가
- [ ] 서점으로 바로가기 로직 수정 && 책 상세 페이지 리팩토링
- [ ] POST 시 localStorage에서 아이템 지워주기

## 🎸 ETC
기타사항
