### ISSUE TITLE
[FEATURE] Filter 기능 개선

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#197]
## 📄 Description
필터 기능을 개선하여 조금 더 자연스럽습니다.

## ✅ TODO
- [ ] 필터 커스텀 훅 변경
- [ ] my page 유저가 업로드한 Feed 부분 개선
- [ ] 마이 페이지 위시 부분 개선
- [ ] 마이 페이지 작성한 챌린지 부분 개선
- [ ] 메인 페이지 개선

## 🎸 ETC
기타사항
