### ISSUE TITLE
[FEAT] 메인(랜딩)페이지 구현

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#20]
## 📄 Description
처음 사이트에 접속했을 때 나올 화면을 구현합니다. 

## ✅ TODO
- [x] 풀스크린 스크롤 테스트 (with Swiper.js)
- [x] 웰컴 페이지 구현
- [x] 인생책 소개 페이지 구현
- [x] 스토리 소개 페이지 구현
- [x] 챌린지 소개 페이지 구현 
- [x] 푸터 구현
---
- [ ] API 호출
- [ ] Link 이용하여 각 카테고리 페이지로 보내기
- [ ] Link 이용하여 각 게시물 상세 페이지로 보내기 (로그인 X일 경우, 로그인 페이지로)

## 🎸 ETC
- 헤더 구현 시 메인페이지는 색깔 다르게(검정바탕, 흰 아이콘) 해야함
- 푸터는 이미지로 넣기
