### ISSUE TITLE
[FEATURE] 조회 모달 삭제 수정 버튼 추가

### ISSUE THREAD

**Issue by eunjin210** [kakao-tech-campus-2nd-step3/Team15_FE#200]
## 📄 Description
조회 모달의 수정과 삭제 버튼을 추가합니다

## ✅ TODO
- [x] 스토리 추가 삭제
- [x] 인생책 추가 삭제
- [x] 독서일기 추가 삭제
- [x] 챌린지 인증글 추가 삭제
