### ISSUE TITLE
[REFACTOR] 수정 삭제 오류 리팩토링

### ISSUE THREAD

**Issue by eunjin210** [kakao-tech-campus-2nd-step3/Team15_FE#212]
## 📄 Description
수정 삭제 오류를 리팩토링 합니다

## ✅ TODO
- [x] 수정 오류 수정
- [x] 삭제 후 reload 추가
- [x] 챌린지 상세 날짜 수정

## 🎸 ETC
기타사항
