### ISSUE TITLE
[FEAT] 메인페이지용 헤더 구현

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#23]
## 📄 Description
사이트의 메인페이지를 위한 헤더 컴포넌트 구현입니다.
## ✅ TODO
- [x] swiper.js 테스트
- [x] 헤더 구현 (with react-icons)
- [ ] 반응형 사이즈 구현

## 🎸 ETC
반응형은 페이지 구현 후 한 번에 하기로 한다.
