### ISSUE TITLE
[STYLE] 전반적인 CSS 수정

### ISSUE THREAD

**Issue by joshuayeyo** [kakao-tech-campus-2nd-step3/Team15_FE#95]
## 📄 Description
깨지는 CSS를 수정합니다.

## ✅ TODO
- [x] 랜딩 페이지 CSS 수정
  - [x] 랜딩 items 깨지는 부분
  - [x] 로고 깨지는 부분
  - [x] 푸터 깨지는 부분
- [x] 글 조회 모달 CSS 수정
  - [x] 요소 높이 수정 (Modal 영역 안빠져나가게)
- [x] 글 작성 모달 CSS 수정
  - [x] 좌우 반으로 나누기
  - [x] 요소 높이 수정 (Modal 영역 안빠져나가게)
- [x] 챌린지 작성 CSS 수정

## 🎸 ETC
# 브라우저 꼭 Chrome 사용해 확인할 것
